version: "3.3"
services:
  tor:
    build:
      context: .
      dockerfile: tor/Dockerfile
    command: /usr/bin/tor
    ports:
      - "9050:9050"
      - "9051:9051"
  python:
    build:
      context: .
      dockerfile: python/Dockerfile
    command: python /code/script.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8888:8888"
    depends_on:
      - tor
